// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2taM3HKUTLZ_ooOSJY7f0fv5M3kPWeR0',
    appId: '1:357073663430:web:12cd61fb1b5c91fd17aec7',
    messagingSenderId: '357073663430',
    projectId: 'bikex-flutter-app',
    authDomain: 'bikex-flutter-app.firebaseapp.com',
    storageBucket: 'bikex-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB8ySnKqc2kWjOgdz_Zf_i7gSarKrZljQ',
    appId: '1:357073663430:android:36024fb87f293e5517aec7',
    messagingSenderId: '357073663430',
    projectId: 'bikex-flutter-app',
    storageBucket: 'bikex-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ptCGt3s9pLm_49-3tLSluZ3gBayybCA',
    appId: '1:357073663430:ios:0a910e0684d35d9c17aec7',
    messagingSenderId: '357073663430',
    projectId: 'bikex-flutter-app',
    storageBucket: 'bikex-flutter-app.firebasestorage.app',
    iosBundleId: 'com.anas.bikex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ptCGt3s9pLm_49-3tLSluZ3gBayybCA',
    appId: '1:357073663430:ios:fba1fa8598fe27e517aec7',
    messagingSenderId: '357073663430',
    projectId: 'bikex-flutter-app',
    storageBucket: 'bikex-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2taM3HKUTLZ_ooOSJY7f0fv5M3kPWeR0',
    appId: '1:357073663430:web:4aa6adab61ea6fed17aec7',
    messagingSenderId: '357073663430',
    projectId: 'bikex-flutter-app',
    authDomain: 'bikex-flutter-app.firebaseapp.com',
    storageBucket: 'bikex-flutter-app.firebasestorage.app',
  );

}